language: python
sudo: false
python:
  - '3.5'
  - '3.6'
env:
  - DJANGO="Django>=1.11,<1.12.0"
  - DJANGO="Django>=2.2,<2.3"
install:
  - pip install -q $DJANGO
  - pip install -q -r test_reqs.txt
script:
  - flake8 runtests.py pageblocks
  - python runtests.py
