language: python
python:
  - '2.7'
  - '3.6'
env:
  - DJANGO="Django>=1.11,<1.12.0"
  - DJANGO="Django>=2.2,<2.3"
matrix:
  exclude:
    - python: '2.7'
      env: DJANGO="Django>=2.2,<2.3"
install:
  - pip install -q $DJANGO
  - pip install -q -r test_reqs.txt
script:
  - flake8 runtests.py
  - python runtests.py
