# Generated by Django 3.2.25 on 2024-07-05 20:44

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pageblocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageblock',
            name='image',
            field=sorl.thumbnail.fields.ImageWithThumbnailsField(upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='imagepullquoteblock',
            name='image',
            field=sorl.thumbnail.fields.ImageWithThumbnailsField(upload_to='images/%Y/%m/%d'),
        ),
    ]
