# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageblocks', '0002_simpleimageblock'),
    ]

    operations = [
    ]
